# 13_export_figures.R
# -----------------------------------------------------------------------
# Copy the main-text figures into the submission folder under their journal numbers.
#
# WHY THIS IS A SCRIPT. It used to be a one-off shell command run by hand. The cohort then changed
# (10 studies excluded as not lung transplant recipients) and every analysis figure was regenerated by
# run_all.R — but the exported Figure1-5.pdf were not, because nothing re-ran the copy. The submitted
# figures said n = 1,073 while the manuscript said 1,063, and three independent reviewers caught it before
# we did. Anything that has to happen after an analysis change belongs in the pipeline, not in a shell
# history.
#
# The order of FIGS IS the figure numbering, and it must match the vector in manuscript.Rmd's legends
# chunk. Mismatch there silently renumbers every prose callout, so it is asserted below.
# -----------------------------------------------------------------------
if (!exists("an")) source(local({ d <- normalizePath(getwd(), "/"); while (!file.exists(file.path(d, "renv.lock")) && dirname(d) != d) d <- dirname(d); file.path(d, "analysis", "00_setup.R") }))

FIGS <- c("F_corpus_flow", "F_completeness_landscape", "F_interpretability",
          "F_item_trends", "F_confounding")
out <- file.path(project_root, "publication/manuscript/figures")
dir.create(out, recursive = TRUE, showWarnings = FALSE)

# The manuscript is the authority on numbering; fail loudly rather than export a set that disagrees.
ms <- file.path(project_root, "publication/manuscript/manuscript.Rmd")
if (file.exists(ms)) {
  txt <- paste(readLines(ms, warn = FALSE), collapse = "\n")
  blk <- regmatches(txt, regexpr('for \\(id in c\\("F_[^)]*\\)', txt))
  if (length(blk)) {
    in_ms <- regmatches(blk, gregexpr('F_[a-z_]+', blk))[[1]]
    if (!identical(in_ms, FIGS))
      stop(sprintf("13_export_figures: figure order disagrees with manuscript.Rmd.\n  here: %s\n  there: %s",
                   paste(FIGS, collapse = ", "), paste(in_ms, collapse = ", ")), call. = FALSE)
  }
}

unlink(list.files(out, pattern = "^Figure", full.names = TRUE))
n <- 0
for (i in seq_along(FIGS)) {
  for (ext in c("pdf", "png")) {
    from <- file.path(dir_figures, paste0(FIGS[i], ".", ext))
    if (!file.exists(from)) stop(sprintf("13_export_figures: missing %s", from), call. = FALSE)
    file.copy(from, file.path(out, sprintf("Figure%d.%s", i, ext)), overwrite = TRUE)
    n <- n + 1
  }
}
message(sprintf("13 complete: %d files exported to publication/manuscript/figures (%s).",
                n, paste(sprintf("Figure%d=%s", seq_along(FIGS), FIGS), collapse = ", ")))
